djangoapp/djangoapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("lmsbaikal/", include("lmsbaikal.urls"))
]

djangoapp/lmsbaikal/urls.py
from django.contrib import admin
from django.urls import path
from .views import QuestionDetailView, QuestionListView, QuestionNewView, QuestionUpdateView, QuestionAnswersAddView


urlpatterns = [
    path("", QuestionListView.as_view()),
    path("<int:pk>/", QuestionDetailView.as_view()),
    path("question-add/", QuestionNewView.as_view()),
    path("question-edit/<int:pk>/", QuestionUpdateView.as_view()),
    path("question-edit/<int:pk>/answer-add/", QuestionAnswersAddView.as_view())
]

djangoapp/lmsbaikal/models.py
"""
Модуль содержит модели приложений.
"""
from django.utils import timezone

from django.db import models


class Question(models.Model):
    """ Модель вопроса. """
    name = models.CharField(max_length=50)
    question_text = models.CharField(max_length=200)
    course_id = models.IntegerField(default=0)
    course_module_id = models.IntegerField(default=0)
    tags = models.CharField(max_length=500)
    penalty = models.FloatField(default=1.0)
    publication_date = models.DateTimeField("date published", default=timezone.now)
    changed_date = models.DateTimeField("date changed", default=timezone.now)

    def __str__(self): # pylint: disable=invalid-str-returned

        return self.name

    def get_tags_count(self):
        """ Получает количество тегов вопроса """

        return len(self.tags.split(",")) # pylint: disable=no-member


class QuestionAnswers(models.Model): # pylint: disable=too-few-public-methods
    """ Модель ответа вопроса. """
    question = models.ForeignKey(Question, on_delete=models.CASCADE, default=1)
    answer = models.CharField(max_length=500)
    answer_format = models.IntegerField(default=0)
    fraction = models.FloatField(default=1.0)
    feedback = models.CharField(max_length=50, default=0)
    feedback_format = models.IntegerField(default=0)

    def __str__(self): # pylint: disable=invalid-str-returned

        return self.answer

djangoapp/lmsbaikal/views.py
"""
Модуль содержит представления приложения.
"""
from django.views.generic import DetailView, ListView, CreateView, UpdateView

from .models import Question, QuestionAnswers


class QuestionListView(ListView): # pylint: disable=too-few-public-methods
    """ CBV-представление списка вопросов. """
    model = Question


class QuestionDetailView(DetailView): # pylint: disable=too-few-public-methods
    """ CBV-представление детальной страницы вопроса. """
    model = Question


class QuestionNewView(CreateView): # pylint: disable=too-many-ancestors,too-few-public-methods
    """ CBV-представление страницы с формой добавления вопроса. """
    model = Question
    fields = "__all__"
    success_url = "/lmsbaikal/"


class QuestionUpdateView(UpdateView): # pylint: disable=too-many-ancestors,too-few-public-methods
    """ CBV-представление страницы с формой редактирования вопроса. """
    model = Question
    fields = "__all__"
    success_url = "/lmsbaikal/"


class QuestionAnswersAddView(CreateView): # pylint: disable=too-many-ancestors,too-few-public-methods
    """ CBV-представление страницы с формой добавления вариантов ответов для вопроса. """
    model = QuestionAnswers
    fields = "__all__"
    success_url = "/lmsbaikal/"

djangoapp/lmsbaikal/templates/lmsbaikal/index.html
{% if question_list %}
    <ul>
    {% for question in question_list %}
        <li><a href="/lmsbaikal/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

djangoapp/lmsbaikal/templates/lmsbaikal/question_detail.html
{% extends "base.html" %}

{% block title %}
    <title>Страница вопроса</title>
    {% endblock %}

{% block content %}
    <h1>{{ object.question_text }}</h1>
    {% if object.questionanswers_set.all %}
        <ul>
        {% for answer in object.questionanswers_set.all %}
            <li>{{ answer.answer }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Для данного вопроса ответы находятся в проработке</p>
    {% endif %}
    <a href="/lmsbaikal/question-edit/{{ question.id }}/answer-add">Добавить ответ</a>
    <a class="btn btn-primary" href="/lmsbaikal/" role="button">Список вопросов</a>
{% endblock %}

djangoapp/lmsbaikal/templates/lmsbaikal/question_form.html
{% extends "base.html" %}

{% block title %}
    <title>Создание и редактирование вопроса</title>
{% endblock %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="=btn btn-primary">Сохранить</button>
</form>

{% endblock %}

djangoapp/lmsbaikal/templates/lmsbaikal/question_list.html
{% extends "base.html" %}

{% block title %}
    <title>Список вопросов</title>
    {% endblock %}
{% block content %}
    {% if object_list %}
        <ul class="list-group">
        {% for question in object_list %}
            <li class="list-group-item">
                <a href="/lmsbaikal/{{ question.id }}/">{{ question.question_text }}</a>
                <span>
                    <a class="btn btn-outline-secondary" href="/lmsbaikal/question-edit/{{ question.id }}/">Редактировать</a>
                </span>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Вопросов пока нет</p>
    {% endif %}
<a href="question-add/">Добавить вопрос</a>
{% endblock %}

djangoapp/lmsbaikal/templates/lmsbaikal/questionanswers_form.html
{% extends "base.html" %}

{% block title %}
    <title>Добавление и редактирование ответа</title>
{% endblock %}

{% block content %}

<form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="=btn btn-primary">Сохранить</button>
</form>

{% endblock %}

djangoapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Title</title>
    {% endblock %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">LMS Baikal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="/lmsbaikal/">Список вопросов</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<div class="container">
    <div class="row">
      {% block content %}

      {% endblock %}
    </div>
</div>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</body>
</html>